routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('service', function () {
    return view('service');
})->name('service');

Route::get('/about', function () {
    return view('about');
})->name('about');

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::get('/booknow', [HomeController::class, 'userBookStore'])->name('booknow');

Route::get('/booked{id}', [HomeController::class, 'userHotelBookStore'])->name('booked');

Route::post('/ajaxPostBookDetails', [HomeController::class, 'ajaxPostBookDetails'])->name('ajaxPostBookDetails');

Route::get('/viewbooking', [HomeController::class, 'userBookView'])->name('viewbooking');

Route::post('/cancelBooking/{id}/{roomno}', [HomeController::class, 'userDestroy'])->name('cancelBooking');

// -- Admin -- //

Route::get('admin/home', [HomeController::class, 'handleAdmin'])->name('admin.route')->middleware('admin');

Route::resource('admin/hotelDetails', AdminController::class)->middleware('admin');

Route::get('admin/staffRegister', [AdminController::class, 'staffRegistration'])->name('admin.staffRegistration')->middleware('admin');

Route::post('admin/staffRegister', [AdminController::class, 'staffRegistrationStore'])->name('admin.staffRegistrationStore')->middleware('admin');

Route::get('admin/staffList', [AdminController::class, 'staffList'])->name('admin.staffList')->middleware('admin');

Route::post('admin/staffDestroy{id}', [AdminController::class, 'staffDestroy'])->name('admin.staffDestroy')->middleware('admin');

// -- Staff -- //

Route::get('staff/home', [HomeController::class, 'handleStaff'])->name('staff.route')->middleware('staff');

Route::get('staff/userapprove', [HomeController::class, 'userApproveByStaff'])->name('staff.userapprove')->middleware('staff');

Route::get('staff/approve{id}', [HomeController::class, 'approve'])->name('staff.approve')->middleware('staff');

Route::get('staff/reject/{id}/{hotel_id}', [HomeController::class, 'reject'])->name('staff.reject')->middleware('staff');

Route::get('staff/roomdetails{id}', [HomeController::class, 'roomdetails'])->name('staff.roomdetails')->middleware('staff');

Route::get('staff/userCheckOut', [HomeController::class, 'userCheckOut'])->name('staff.userCheckOut')->middleware('staff');

Route::get('staff/checkout/{id}/{hotel_id}', [HomeController::class, 'checkout'])->name('checkout')->middleware('staff');;

Route::get('staff/ajaxGetUserDetails/{id}', [HomeController::class, 'ajaxGetUserDetails'])->name('staff.ajaxGetUserDetails')->middleware('staff');

resources/views/admin/handleAdmin.blade.php
@extends('layouts.applcp')

@section('content')
Hey! you are admin.
@endsection

@section('js_files')
@endsection

@section('js_script')
@endsection

@section('css_files')
@endsection

@section('css_custom')
@endsection

resources/views/admin/hotelDetails.blade.php
@extends('layouts.applcp')

@section('content')
@if(session()->has('success'))
<div class="alert alert-success">
  {{ session()->get('success') }}
</div>
@endif
@if(session()->has('warning'))
<div class="alert alert-danger">
  {{ session()->get('warning') }}
</div>
@endif
<div class="card">
  <h3 class="card-header text-center font-weight-bold text-uppercase py-4">View Book Table</h3>
  <div class="card-body">
    <div id="table" class="table-editable">
      <span class="table-add float-right mb-3 mr-2"><a href="{{route('hotelDetails.create')}}" class="text-success"><i class="fas fa-plus fa-2x" aria-hidden="true"></i></a></span>
      <table class="table table-bordered table-responsive-md table-striped text-center">
        <thead>
          <tr>
            <th class="text-center">Room No</th>
            <th class="text-center">Cost</th>
            <th class="text-center">Category</th>
            <th class="text-center">Guest No</th>
            <th class="text-center">Room Size</th>
            <th class="text-center">Image</th>
            <th class="text-center">Edit</th>
            <th class="text-center">Remove</th>
          </tr>
        </thead>
        <tbody>
          <input type="hidden" value="{{$i=0}}" />
          @foreach($data as $datas)
          <tr>
            <td class="">{{$datas->room_no}} </td>
            <td class="">{{$datas->cost}}</td>
            <td class="">{{$datas->category}}</td>
            <td class="">{{$datas->guest_no}}</td>
            <td class="">{{$datas->room_size}}</td>
            <td class="">

              <img src="{{asset('images/'.$datas->imagepath)}}" style=" height: 75px;width: 100px;margin-top: 0.5rem; margin-bottom: 0.2rem;" />
            </td>
            <td><span class="table-edit"> <a class="btn btn-primary btn-rounded btn-sm my-0" href="{{route('hotelDetails.edit',$datas->id)}}">UPDATE </a></td></span>
            <td>
              <form action="{{route('hotelDetails.destroy',$datas->id)}}" method="POST">
                {{ method_field('DELETE') }}
                @csrf
                <button type="submit" class="btn btn-danger btn-rounded btn-sm my-0" style="margin-right: 0.5rem;" href="{{route('hotelDetails.destroy',$datas->id)}}"> DELETE </button>
            </td>
            </form>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection

@section('js_files')
@endsection

@section('js_script')
@endsection

@section('css_files')
@endsection

@section('css_custom')
@endsection

resources/views/admin/hotelDetailsEdit.blade.php
@extends('layouts.applcp')

@section('content')
<div class="card card-custom">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card-header">
        <h3 class="card-title">
            Update Hotel Details
        </h3>
    </div>
    <!--begin::Form-->
    <form class="form" method="POST" action="{{route('hotelDetails.update',$data->id)}}" enctype="multipart/form-data">
        {{method_field('PUT')}}
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label>Room No </label>
                <input type="text" class="form-control form-control-lg @error('room_no') is-invalid @enderror" id="room_no" placeholder="Room No" name="room_no" value="{{$data->room_no}}" />
                @error('room_no')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleSelectl">Category</label>
                <select class="form-control form-control-lg @error('category') is-invalid @enderror" id="category" name="category">
                    <option value="Single" {{$data->category == 'King' ? 'selected':''}}>Single</option>
                    <option value="Double" {{$data->category == 'Double' ? 'selected':''}}>Double</option>
                    <option value="King" {{$data->category == 'Double' ? 'selected':''}}>King</option>
                </select>    
                     @error('category')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label>Cost </label>
                <input type="text" class="form-control form-control-lg @error('cost') is-invalid @enderror" id="cost" placeholder="Cost" name="cost" value="{{$data->cost}}" />
                @error('cost')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label>No of Guest </label>
                <input type="text" id="guest_no" class="form-control form-control-lg @error('guest_no') is-invalid @enderror" placeholder="No Of Guest" name="guest_no" value="{{$data->guest_no}}" />
                @error('guest_no')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror   </div>

            <div class="form-group">
                <label>Room Size </label>
                <input type="text" id="room_size" class="form-control form-control-lg @error('room_size') is-invalid @enderror" placeholder="Room Size in Sqft" name="room_size" value="{{$data->room_size}}" />
                @error('room_size')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <input type="hidden" class="form-control form-control-lg " placeholder="Room Size in Sqft" name="image" value="{{$data->imagepath}}" />
      
    
            <div class="form-group">
                <label>Photo</label>
                <input type="file" class="form-control form-control-lg @error('title') is-invalid @enderror" placeholder="Photo" id="imagepath" name="imagepath" value=""/>
                @error('imagepath')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="card-footer">
                <button type="Submit" class="btn btn-success mr-2">Submit</button>
                <button type="reset" class="btn btn-secondary">Cancel</button>
                
            </div>
    </form>
    <!--end::Form-->
</div>
@endsection

resources/views/admin/hotelDetailsInsert.blade.php
@extends('layouts.applcp')

@section('content')
<div class="card card-custom">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="card-header">
        <h3 class="card-title">
            Hotel Details
        </h3>
    </div>
    <!--begin::Form-->
    <form class="form" method="POST" action="{{route('hotelDetails.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label>Room No </label>
                <input type="text" class="form-control form-control-lg @error('room_no') is-invalid @enderror " placeholder="Room No" name="room_no" id="room_no"/>
                @error('room_no')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleSelectl">Category</label>
                <select class="form-control form-control-lg @error('category') is-invalid @enderror" id="category" name="category">
                    <option value="Single">Single</option>
                    <option value="Double">Double</option>
                    <option value="King">King</option>
                </select>
                @error('category')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror

            </div>
            <div class="form-group">
                <label>Cost </label>
                <input type="text" class="form-control form-control-lg @error('cost') is-invalid @enderror" id="cost" placeholder="Cost" name="cost" />
                @error('cost')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label>No of Guest </label>
                <input type="text" class="form-control form-control-lg @error('title') is-invalid @enderror" placeholder="No Of Guest" name="guest_no" id="guest_no" />
                @error('guest_no')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label>Room Size </label>
                <input type="text" class="form-control form-control-lg @error('room_size') is-invalid @enderror " placeholder="Room Size in Sqft" name="room_size" id="room_size" />
                @error('room_size')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label>Photo</label>
                <input type="file" class="form-control form-control-lg @error('imagepath') is-invalid @enderror " placeholder="Photo" name="imagepath" id="imagepath" />
                @error('imagepath')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="card-footer">
                <button type="Submit" class="btn btn-success mr-2">Submit</button>
                <button type="reset" class="btn btn-secondary">Cancel</button>
            </div>
    </form>
    <!--end::Form-->
</div>
@endsection

resources/views/admin/staffRegistration.blade.php
@extends('layouts.applcp')

@section('content')

  @if(session()->has('warning'))
  <div class="alert alert-danger">
    {{ session()->get('warning') }}
  </div>
  @endif

  @if(session()->has('success'))
  <div class="alert alert-success">
    {{ session()->get('success') }}
  </div>
  @endif
  
<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            Staff Registration
        </h3>
    </div>
    <!--begin::Form-->
    <form method="POST" action="{{ route('admin.staffRegistrationStore') }}">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputPassword1">Staff Name<span class="text-danger">*</span></label>
                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label>Email address <span class="text-danger">*</span></label>
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                @error('email')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password <span class="text-danger">*</span></label>
                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                @error('password')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Confirm Password <span class="text-danger">*</span></label>
                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
            </div>
            <input type="hidden" class="form-control" value="2" name="is_admin" placeholder="Password" />
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary mr-2">
                {{ __('Register') }}
            </button>
        </div>

    </form>
    <!--end::Form-->
</div>

@endsection

@section('js_files')
@endsection

@section('js_script')
@endsection

@section('css_files')
@endsection

@section('css_custom')
@endsection

resources/views/admin/stafflist.blade.php
@extends('layouts.applcp')

@section('content')
@if(session()->has('success'))
<div class="alert alert-success">
  {{ session()->get('success') }}
</div>
@endif
@if(session()->has('warning'))
<div class="alert alert-danger">
  {{ session()->get('warning') }}
</div>
@endif
<div class="card">
  <h3 class="card-header text-center font-weight-bold text-uppercase py-4">View User Booking Details</h3>
  <div class="card-body">
    <div id="table" class="table-editable">
      <table class="table table-bordered table-responsive-md table-striped text-center">
        <thead>
          <tr>
            <th class="text-center">Staff Name</th>
            <th class="text-center">Email</th>
            <th class="text-center">Remove Staff</th>

          </tr>
        </thead>
        <tbody>
          @foreach($data as $datas)
          <tr>
            <td class="">{{$datas->name}}</td>
            <td class="">{{$datas->email}} </td>
            <td>
              <form action="{{route('admin.staffDestroy',$datas->id)}}" method="POST">
                @csrf
                <button class="btn btn-danger btn-rounded btn-sm my-0" style="margin-right: 0.5rem;"> Remove Staff </button>
              </form>
              </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

@endsection

@section('js_files')
@endsection

@section('js_script')
@endsection

@section('css_files')
@endsection

@section('css_custom')
@endsection